import mongoose, { type HydratedDocument, type Model } from "mongoose";

export const PRESCRIPTION_STATUSES = ["active", "completed", "revoked"] as const;
export type PrescriptionStatus = (typeof PRESCRIPTION_STATUSES)[number];

/**
 * Stage 4 — Veterinarian Prescription.
 *
 * A prescription can ONLY be created/finalized by an authenticated
 * veterinarian (doctor) or a hospital administrator acting as a reviewer.
 * It is always linked to an AI report AND the veterinarian review that
 * approved/modified it — never generated by the AI model itself.
 */
export interface VeterinaryPrescription {
  petId: mongoose.Types.ObjectId;
  /** The AI report that this prescription is based on (never a source of truth). */
  aiReportId: mongoose.Types.ObjectId;
  /** Veterinarian profile that issued the prescription. */
  veterinarianId: mongoose.Types.ObjectId;
  /** Authenticated account that issued it (audit trail). */
  issuedByAccountId?: string;
  issuedByAccountType?: "patient" | "doctor" | "admin";
  medicineName: string;
  dosage: string;
  frequency: string;
  duration: string;
  route: string;
  additionalInstructions: string;
  /** Decision recorded on the source report at issue time (approve | modify). */
  reviewDecision?: "approve" | "modify" | "reviewed";
  issuedAt: Date;
  status: PrescriptionStatus;
  createdAt?: Date;
  updatedAt?: Date;
}

export type VeterinaryPrescriptionDocument = HydratedDocument<VeterinaryPrescription>;

const veterinaryPrescriptionSchema = new mongoose.Schema<VeterinaryPrescription>(
  {
    petId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "pet",
      required: true,
      index: true
    },
    aiReportId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ai_report",
      required: true,
      index: true
    },
    veterinarianId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "veterinarian",
      required: true,
      index: true
    },
    issuedByAccountId: { type: String },
    issuedByAccountType: { type: String, enum: ["patient", "doctor", "admin"] },
    medicineName: { type: String, required: true, trim: true, maxlength: 180 },
    dosage: { type: String, required: true, trim: true, maxlength: 120 },
    frequency: { type: String, required: true, trim: true, maxlength: 120 },
    duration: { type: String, required: true, trim: true, maxlength: 120 },
    route: { type: String, trim: true, maxlength: 160, default: "" },
    additionalInstructions: { type: String, trim: true, maxlength: 4000, default: "" },
    reviewDecision: { type: String, enum: ["approve", "modify", "reviewed"] },
    issuedAt: { type: Date, required: true, default: Date.now, index: true },
    status: {
      type: String,
      enum: PRESCRIPTION_STATUSES,
      default: "active",
      index: true
    }
  },
  { timestamps: true }
);

veterinaryPrescriptionSchema.index({ petId: 1, issuedAt: -1 });
veterinaryPrescriptionSchema.index({ aiReportId: 1, issuedAt: -1 });
veterinaryPrescriptionSchema.index({ veterinarianId: 1, issuedAt: -1 });

const VeterinaryPrescriptionModel =
  (mongoose.models.veterinary_prescription as Model<VeterinaryPrescription> | undefined) ??
  mongoose.model<VeterinaryPrescription>("veterinary_prescription", veterinaryPrescriptionSchema);

export default VeterinaryPrescriptionModel;