export const AUDIT_EVENT_TYPES = [
  "auth.registration",
  "auth.login.success",
  "auth.login.failure",
  "auth.refresh.reuse_detected",
  "auth.logout",
  "auth.logout_all",
  "auth.email_verified",
  "auth.password_reset",
  "auth.otp.failure",
  "auth.otp.lockout",
  "auth.2fa.setup_started",
  "auth.2fa.enabled",
  "auth.2fa.disabled",
  "auth.2fa.challenge_created",
  "auth.2fa.challenge_success",
  "auth.2fa.challenge_failure",
  "auth.recovery_code.used",
  "auth.recovery_code.regenerated",
  "session.revoked",
  "role.changed",
  "permission.changed",
  "membership.created",
  "membership.changed",
  "membership.revoked",
  "organization.created",
  "organization.updated",
  "doctor.created",
  "patient.health_profile.updated",
  "patient.profile.updated",
  "doctor.availability.updated",
  "appointment.booked",
  "appointment.cancelled",
  "appointment.status_changed",
  "appointment.clinical_notes.updated",
  "medical_record.created",
  "medical_record.updated",
  "medical_record.finalized",
  "family_member.created",
  "family_member.removed",
  "health_card.viewed",
  "admin.sensitive_action",
  "security.cross_tenant_denied"
] as const;

export type AuditEventType = (typeof AUDIT_EVENT_TYPES)[number];
